package com.xworkz.Encapsulation;

public class MainMethod {

	public static void main(String[] args) {

		System.out.println("Invoking MainMethod in WhatsApp");
		WhatsApp whatsapp = new WhatsApp();
		whatsapp.setMessage("Voice Message");
		whatsapp.setCall("Video Call");
		whatsapp.setNoOfGroups(10);
		whatsapp.setViews(100);
		whatsapp.setSpeed("15kbps");
		whatsapp.setBackup("Photoes");
		whatsapp.setStorage("4GB");
		whatsapp.setTheme("Dark Mode");
		whatsapp.setNoOfSticker(50);
		whatsapp.setNoOfContact(200);
		whatsapp.setLanguage("English");
		whatsapp.setArchieveContact(20);
		whatsapp.setStatusPrivacy(true);
		whatsapp.setWhatsAppNo(8799854389l);
		System.out.println(whatsapp.getMessage());
		System.out.println(whatsapp.getCall());
		System.out.println(whatsapp.getNoOfGroups());
		System.out.println(whatsapp.getViews());
		System.out.println(whatsapp.getSpeed());
		System.out.println(whatsapp.getBackup());
		System.out.println(whatsapp.getStorage());
		System.out.println(whatsapp.getTheme());
		System.out.println(whatsapp.getNoOfSticker());
		System.out.println(whatsapp.getNoOfContact());
		System.out.println(whatsapp.getLanguage());
		System.out.println(whatsapp.getArchieveContact());
		System.out.println(whatsapp.isStatusPrivacy());
		System.out.println(whatsapp.getWhatsAppNo());

		System.out.println("=====================================");
		System.out.println("Invoking mainMethod in Instagram");
		Instagram instagram = new Instagram();
		instagram.setNoOfFollowers(350);
		instagram.setNoOfFollowing(200);
		instagram.setPrivacy("Private");
		instagram.setMessage("Voice Message");
		instagram.setNoOfPost(20);
		instagram.setProfile("Photoes");
		instagram.setVideo("Live Video");
		instagram.setStoryViews(220);
		instagram.setSearch(true);
		instagram.setTheme("Light Mode");
		instagram.setNoOflikes(300);
		instagram.setComments(20);
		instagram.setId("sanju_achar");
		instagram.setCall("Video Call");
		System.out.println(instagram.getNoOfFollowers());
		System.out.println(instagram.getNoOfFollowing());
		System.out.println(instagram.getPrivacy());
		System.out.println(instagram.getMessage());
		System.out.println(instagram.getNoOfPost());
		System.out.println(instagram.getProfile());
		System.out.println(instagram.getVideo());
		System.out.println(instagram.getStoryViews());
		System.out.println(instagram.isSearch());
		System.out.println(instagram.getTheme());
		System.out.println(instagram.getNoOflikes());
		System.out.println(instagram.getComments());
		System.out.println(instagram.getId());
		System.out.println(instagram.getCall());

		System.out.println("======================================");
		System.out.println("Invoking mainMethod in SnapChat");
		Snapchat snapchat = new Snapchat();
		snapchat.setTheme("Light theme");
		snapchat.setCloseFriends(20);
		snapchat.setNoOfSnaps(20);
		snapchat.setGroups(5);
		snapchat.setChat("Message");
		snapchat.setFriends(30);
		snapchat.setStoryViews(30);
		snapchat.setNoOfFilters(20);
		snapchat.setFont("Italic");
		snapchat.setMusic(true);
		snapchat.setLocation(true);
		snapchat.setFilters(10);
		snapchat.setPrivacy("Private");
		snapchat.setSnapId("racchu78676");
		System.out.println(snapchat.getTheme());
		System.out.println(snapchat.getCloseFriends());
		System.out.println(snapchat.getNoOfSnaps());
		System.out.println(snapchat.getGroups());
		System.out.println(snapchat.getChat());
		System.out.println(snapchat.getFriends());
		System.out.println(snapchat.getStoryViews());
		System.out.println(snapchat.getNoOfFilters());
		System.out.println(snapchat.getFont());
		System.out.println(snapchat.isMusic());
		System.out.println(snapchat.isLocation());
		System.out.println(snapchat.getFilters());
		System.out.println(snapchat.getPrivacy());
		System.out.println(snapchat.getSnapId());

		System.out.println("=================================");
		System.out.println("Invoking mainMethod in youtube");
		Youtube youtube = new Youtube();
		youtube.setTheme("Dark Mode");
		youtube.setNoOfLikes(1000);
		youtube.setComments(500);
		youtube.setName("Rachana");
		youtube.setYoutubeId("racchu_656665");
		youtube.setFriends(20);
		youtube.setSubcription(10);
		youtube.setLanguage("English");
		youtube.setShare(20);
		youtube.setPrivacy(true);
		youtube.setNoOfAccount(2);
		youtube.setFounder("steve chen");
		youtube.setMembership(true);
		youtube.setHistory(true);
		System.out.println(youtube.getTheme());
		System.out.println(youtube.getNoOfLikes());
		System.out.println(youtube.getComments());
		System.out.println(youtube.getName());
		System.out.println(youtube.getYoutubeId());
		System.out.println(youtube.getFriends());
		System.out.println(youtube.getSubcription());
		System.out.println(youtube.getLanguage());
		System.out.println(youtube.getShare());
		System.out.println(youtube.isPrivacy());
		System.out.println(youtube.getNoOfAccount());
		System.out.println(youtube.getFounder());
		System.out.println(youtube.isMembership());
		System.out.println(youtube.isHistory());

		System.out.println("===================================");
		System.out.println("Invoking mainMethod in Github");
		Github github = new Github();
		github.setAccess("public");
		github.setIssue(true);
		github.setLanguage("English");
		github.setLink("Eclipse");
		github.setNoOfBranches(10);
		github.setNoOfPackages(3);
		github.setNoOfProjects(3);
		github.setNoOfRepo(3);
		github.setNotification(true);
		github.setProfilePic(false);
		github.setRepositoryName("Xworkz");
		github.setProjectName("Sign language");
		github.setTheme("White");
		github.setUserName("Rachana");
		System.out.println(github.isIssue());
		System.out.println(github.getAccess());
		System.out.println(github.getLanguage());
		System.out.println(github.getLink());
		System.out.println(github.getNoOfBranches());
		System.out.println(github.getNoOfPackages());
		System.out.println(github.getNoOfProjects());
		System.out.println(github.getNoOfRepo());
		System.out.println(github.getProjectName());
		System.out.println(github.getRepositoryName());
		System.out.println(github.getTheme());
		System.out.println(github.getUserName());
		System.out.println(github.isNotification());
		System.out.println(github.isProfilePic());

		System.out.println("=================================");
		System.out.println("Invoking mainMethod in Amazon");
		Amazon amazon = new Amazon();
		amazon.setAmount(5000);
		amazon.setCart(true);
		amazon.setLoginId("Rachana");
		amazon.setNoOfUsers(10000);
		amazon.setNotification(true);
		amazon.setOffer(false);
		amazon.setOrder(true);
		amazon.setPaytype("Online");
		amazon.setPrimeSubscription(true);
		amazon.setQos("Good");
		amazon.setQualtityOfProduct("Good");
		amazon.setShoping(true);
		amazon.setTheme("General");
		amazon.setUserName("Rachana N A");
		System.out.println(amazon.getAmount());
		System.out.println(amazon.getLoginId());
		System.out.println(amazon.getNoOfUsers());
		System.out.println(amazon.getPaytype());
		System.out.println(amazon.getQos());
		System.out.println(amazon.getQualtityOfProduct());
		System.out.println(amazon.getTheme());
		System.out.println(amazon.getUserName());
		System.out.println(amazon.isCart());
		System.out.println(amazon.isNotification());
		System.out.println(amazon.isOffer());
		System.out.println(amazon.isOrder());
		System.out.println(amazon.isPrimeSubscription());
		System.out.println(amazon.isShoping());

		System.out.println("===================================");
		System.out.println("Invoking mainMnethod in FaceBook");
		FaceBook facebook = new FaceBook();
		facebook.setFaceBookID("Rachana N A");
		facebook.setEmail("rachanaachar29@gmail.com");
		facebook.setNumber(9980415216l);
		facebook.setPasswrod("racc25hu@");
		facebook.setLanguage("Kanada");
		facebook.setTheme("Dark");
		facebook.setSince(2005);
		facebook.setNoOfFriends(35);
		facebook.setNoOfPosts(20);
		facebook.setFounder("Mark Zuckerberg");
		facebook.setNoOfLikes(150);
		facebook.setAccountType("Private");
		facebook.setNoOfComments(50);
		facebook.setProfilePic(true);
		System.out.println(facebook.getFaceBookID());
		System.out.println(facebook.getEmail());
		System.out.println(facebook.getNumber());
		System.out.println(facebook.getPasswrod());
		System.out.println(facebook.getLanguage());
		System.out.println(facebook.getTheme());
		System.out.println(facebook.getSince());
		System.out.println(facebook.getNoOfFriends());
		System.out.println(facebook.getNoOfPosts());
		System.out.println(facebook.getFounder());
		System.out.println(facebook.getNoOfLikes());
		System.out.println(facebook.getAccountType());
		System.out.println(facebook.getNoOfComments());
		System.out.println(facebook.isProfilePic());

		System.out.println("=====================================");
		System.out.println("Invoking mainmethod in phonepe");
		PhonePe phonePe = new PhonePe();
		phonePe.setLanguage("English");
		phonePe.setTheme("Light");
		phonePe.setBalance(15000);
		phonePe.setAuthentication(true);
		phonePe.setPhonepeNumber(8987888459l);
		phonePe.setNoOfRewards(10);
		phonePe.setUpiNumber(20875);
		phonePe.setPaymentSuccess(false);
		phonePe.setUpiId("rachana@sbi");
		phonePe.setPassword(8967);
		phonePe.setOtp(4325);
		phonePe.setPaymentMethod("QR");
		phonePe.setBankName("State bank of India");
		phonePe.setAccNo(12345542);
		System.out.println(phonePe.getLanguage());
		System.out.println(phonePe.getTheme());
		System.out.println(phonePe.getBalance());
		System.out.println(phonePe.isAuthentication());
		System.out.println(phonePe.getPhonepeNumber());
		System.out.println(phonePe.getNoOfRewards());
		System.out.println(phonePe.getUpiNumber());
		System.out.println(phonePe.isPaymentSuccess());
		System.out.println(phonePe.getUpiId());
		System.out.println(phonePe.getPassword());
		System.out.println(phonePe.getOtp());
		System.out.println(phonePe.getPaymentMethod());
		System.out.println(phonePe.getBankName());
		System.out.println(phonePe.getAccNo());

		System.out.println("=================================");
		System.out.println("Invoking mainMethod in Netflix");
		Netflix netflix = new Netflix();
		netflix.setSubcription(true);
		netflix.setTheme("Light");
		netflix.setAccountName("Rachana");
		netflix.setLanguage("Kannada");
		netflix.setAccountPrivacy("Private");
		netflix.setStreamQuality("HD");
		netflix.setNoOfusers(1000);
		netflix.setLoginId("racchu@456");
		netflix.setContent("Movies");
		netflix.setOfflineViewing(false);
		netflix.setDownload(true);
		netflix.setAmount(299);
		netflix.setPassword("6767@98");
		netflix.setFounder(" Scootts Valley");
		System.out.println(netflix.isSubcription());
		System.out.println(netflix.getTheme());
		System.out.println(netflix.getAccountName());
		System.out.println(netflix.getLanguage());
		System.out.println(netflix.getAccountPrivacy());
		System.out.println(netflix.getStreamQuality());
		System.out.println(netflix.getNoOfusers());
		System.out.println(netflix.getLoginId());
		System.out.println(netflix.getContent());
		System.out.println(netflix.isOfflineViewing());
		System.out.println(netflix.isDownload());
		System.out.println(netflix.getAmount());
		System.out.println(netflix.getPassword());
		System.out.println(netflix.getFounder());

		System.out.println("================================");
		System.out.println("Invoking mainMethod in Linkedin");
		LinkedIn linkedIn = new LinkedIn();
		linkedIn.setAccess("Public");
		linkedIn.setChat("Text");
		linkedIn.setConnections(300);
		linkedIn.setCreatorMode("Off");
		linkedIn.setEducation("BE");
		linkedIn.setExperience(false);
		linkedIn.setLikes(80);
		linkedIn.setName("Rachana N A");
		linkedIn.setNetwork("Open access");
		linkedIn.setNotification(true);
		linkedIn.setPosts(2);
		linkedIn.setProfilePic(true);
		linkedIn.setSupports(30);
		linkedIn.setSince(2022);
		System.out.println(linkedIn.getAccess());
		System.out.println(linkedIn.getChat());
		System.out.println(linkedIn.getConnections());
		System.out.println(linkedIn.getCreatorMode());
		System.out.println(linkedIn.getEducation());
		System.out.println(linkedIn.getLikes());
		System.out.println(linkedIn.getName());
		System.out.println(linkedIn.getNetwork());
		System.out.println(linkedIn.getPosts());
		System.out.println(linkedIn.getSince());
		System.out.println(linkedIn.getSupports());
		System.out.println(linkedIn.isExperience());
		System.out.println(linkedIn.isNotification());
		System.out.println(linkedIn.isProfilePic());

		System.out.println("===================================");
		System.out.println("Invoking mainMethod in Pubg");
		System.out.println("invoking Pubg in main");
		Pubg pubg = new Pubg();
		pubg.setGameName("pubg MobileLite");
		pubg.setVoice(true);
		pubg.setNoOfPlayers(4);
		pubg.setSince(2000);
		pubg.setVehicle("Bike");
		pubg.setWeapon("Gun");
		pubg.setTeamMembers(30);
		pubg.setChickenDinner(true);
		pubg.setEnemyCount(4);
		pubg.setWeather("Rain");
		pubg.setFootStep(true);
		pubg.setVehicleSpeed(60);
		pubg.setFounder("Greene");
		pubg.setRating(3);
		System.out.println(pubg.getGameName());
		System.out.println(pubg.isVoice());
		System.out.println(pubg.getNoOfPlayers());
		System.out.println(pubg.getSince());
		System.out.println(pubg.getVehicle());
		System.out.println(pubg.getWeapon());
		System.out.println(pubg.getTeamMembers());
		System.out.println(pubg.isChickenDinner());
		System.out.println(pubg.getEnemyCount());
		System.out.println(pubg.getWeather());
		System.out.println(pubg.isFootStep());
		System.out.println(pubg.getVehicleSpeed());
		System.out.println(pubg.getFounder());
		System.out.println(pubg.getRating());

		System.out.println("===================================");
		System.out.println("Invoking mainMethod in Redbus");
		Redbus redbus = new Redbus();
		redbus.setPayment("Online Payment");
		redbus.setSms(true);
		redbus.setLanguage("English");
		redbus.setNoOfUsers(100000);
		redbus.setBookingType("Online");
		redbus.setAmount(560);
		redbus.setNoOfTicket(1);
		redbus.setSeatSelection(true);
		redbus.setBusTypes("Sleeper");
		redbus.setDiscount(false);
		redbus.setAccountName("Rachana");
		redbus.setReviews("Good");
		redbus.setGroupBooking(false);
		redbus.setBookingId("rachana4533");
		System.out.println(redbus.getPayment());
		System.out.println(redbus.isSms());
		System.out.println(redbus.getLanguage());
		System.out.println(redbus.getNoOfUsers());
		System.out.println(redbus.getBookingType());
		System.out.println(redbus.getAmount());
		System.out.println(redbus.getNoOfTicket());
		System.out.println(redbus.isSeatSelection());
		System.out.println(redbus.getBusTypes());
		System.out.println(redbus.isDiscount());
		System.out.println(redbus.getAccountName());
		System.out.println(redbus.getReviews());
		System.out.println(redbus.isGroupBooking());
		System.out.println(redbus.getBookingId());

		System.out.println("===================================");
		System.out.println("Invoking mainMethod in Irctc");
		Irctc irctc = new Irctc();
		irctc.setBooking(true);
		irctc.setDate(20);
		irctc.setFrom("Banglore");
		irctc.setNotification(true);
		irctc.setNumberOfSeats(3);
		irctc.setPricePerTicket(200);
		irctc.setReservationType("General");
		irctc.setSeatAvailable(true);
		irctc.setSeatConfirmation(true);
		irctc.setSeatNumber(75);
		irctc.setTime(12);
		irctc.setTo("Narasimharajapura");
		irctc.setTrainName("Siddaganga");
		irctc.setTrainNumber(12725);
		System.out.println(irctc.getDate());
		System.out.println(irctc.getFrom());
		System.out.println(irctc.getNumberOfSeats());
		System.out.println(irctc.getPricePerTicket());
		System.out.println(irctc.getReservationType());
		System.out.println(irctc.getSeatNumber());
		System.out.println(irctc.getTime());
		System.out.println(irctc.getTo());
		System.out.println(irctc.getTrainName());
		System.out.println(irctc.getTrainNumber());
		System.out.println(irctc.isBooking());
		System.out.println(irctc.isNotification());
		System.out.println(irctc.isSeatAvailable());
		System.out.println(irctc.isSeatConfirmation());

		System.out.println("=====================================");
		System.out.println("Invoking mainMethod in NammaYathri");
		NammaYatri nammayatri = new NammaYatri();
		nammayatri.setPrice(50);
		nammayatri.setCurrentLocation("Rajajinagar");
		nammayatri.setDestination("Malleshwaram");
		nammayatri.setOtp(1234);
		nammayatri.setNoOfPeople(3);
		nammayatri.setLanguage("English");
		nammayatri.setNoOfRides(2);
		nammayatri.setContactNo(876398798l);
		nammayatri.setCancellationRate(50);
		nammayatri.setPaymentType("Online");
		nammayatri.setNoPlateColor("Yellow");
		nammayatri.setUserName("Rachana");
		nammayatri.setVehicleNo("KA-01 9061");
		nammayatri.setPassword("67@45R");
		System.out.println(nammayatri.getPrice());
		System.out.println(nammayatri.getCurrentLocation());
		System.out.println(nammayatri.getDestination());
		System.out.println(nammayatri.getOtp());
		System.out.println(nammayatri.getNoOfPeople());
		System.out.println(nammayatri.getLanguage());
		System.out.println(nammayatri.getNoOfRides());
		System.out.println(nammayatri.getContactNo());
		System.out.println(nammayatri.getCancellationRate());
		System.out.println(nammayatri.getPaymentType());
		System.out.println(nammayatri.getNoPlateColor());
		System.out.println(nammayatri.getUserName());
		System.out.println(nammayatri.getVehicleNo());
		System.out.println(nammayatri.getPassword());

		System.out.println("=====================================");
		System.out.println("Invoking mainMethod in Rapido");
		System.out.println("Invoking Rapido in main");
		Rapido rapido = new Rapido();
		rapido.setConfiramtion(true);
		rapido.setCost(250);
		rapido.setCurrentLocation("Rajajinagar");
		rapido.setDropLocation("Malleshwaram");
		rapido.setLanguage("Kannada");
		rapido.setNumber(9611965471l);
		rapido.setOnTime(true);
		rapido.setOtp(542615);
		rapido.setPayMode("Cash");
		rapido.setRating(4);
		rapido.setRides(3);
		rapido.setTime(6);
		rapido.setUserName("Rachana");
		rapido.setVehicle("Bike");
		System.out.println(rapido.getCost());
		System.out.println(rapido.getCurrentLocation());
		System.out.println(rapido.getDropLocation());
		System.out.println(rapido.getLanguage());
		System.out.println(rapido.getNumber());
		System.out.println(rapido.getOtp());
		System.out.println(rapido.getPayMode());
		System.out.println(rapido.getRating());
		System.out.println(rapido.getRides());
		System.out.println(rapido.getTime());
		System.out.println(rapido.getUserName());
		System.out.println(rapido.getVehicle());
		System.out.println(rapido.isConfiramtion());
		System.out.println(rapido.isOnTime());

		System.out.println("=====================================");
		System.out.println("Invoking mainMethod in Uber");
		Uber uber = new Uber();
		uber.setConfirmation(true);
		uber.setCost(250);
		uber.setCurrentLocation("Mejestic");
		uber.setDestination("Vijayanagar");
		uber.setEmail("racchu@8899");
		uber.setMobileNumber(9611965471l);
		uber.setNoOfPeople(3);
		uber.setNoOfRides(2);
		uber.setOtp(566466);
		uber.setPaymentMode("Online");
		uber.setRating(5);
		uber.setUserName("Rachana");
		uber.setVehicle("Auto");
		uber.setVehicleNumber("KA1346");
		System.out.println(uber.getCost());
		System.out.println(uber.getCurrentLocation());
		System.out.println(uber.getDestination());
		System.out.println(uber.getEmail());
		System.out.println(uber.getMobileNumber());
		System.out.println(uber.getNoOfPeople());
		System.out.println(uber.getNoOfRides());
		System.out.println(uber.getOtp());
		System.out.println(uber.getPaymentMode());
		System.out.println(uber.getRating());
		System.out.println(uber.getUserName());
		System.out.println(uber.getVehicle());
		System.out.println(uber.getVehicleNumber());
		System.out.println(uber.isConfirmation());

		System.out.println("=====================================");
		System.out.println("Invoking mainMethod in Ola");
		Ola ola = new Ola();
		ola.setEmail("rachananrp@gmail.com");
		ola.setUserName("Rachana NA");
		ola.setMobileNumber(8884992748l);
		ola.setCurrentLocation("jayanagr");
		ola.setDestinationLocation("Majestic");
		ola.setProfilePic(true);
		ola.setVehicle("Car");
		ola.setNoOfPeople(4);
		ola.setOtp(5431);
		ola.setPaymentMethod("Online");
		ola.setVehicleNumber("KA146709");
		ola.setNoOfRides(20);
		ola.setCost(50);
		ola.setCancellationRate(20);
		System.out.println(ola.getEmail());
		System.out.println(ola.getUserName());
		System.out.println(ola.getMobileNumber());
		System.out.println(ola.getCurrentLocation());
		System.out.println(ola.getDestinationLocation());
		System.out.println(ola.isProfilePic());
		System.out.println(ola.getVehicle());
		System.out.println(ola.getNoOfPeople());
		System.out.println(ola.getOtp());
		System.out.println(ola.getPaymentMethod());
		System.out.println(ola.getVehicleNumber());
		System.out.println(ola.getNoOfRides());
		System.out.println(ola.getCost());
		System.out.println(ola.getCancellationRate());

		System.out.println("=====================================");
		System.out.println("Invoking mainMethod in NammaMetro");
		NammaMetro nammaMetro = new NammaMetro();
		nammaMetro.setLanguage("English");
		nammaMetro.setFromStation("Rajajinagar");
		nammaMetro.setToStation("Mejestic");
		nammaMetro.setFare(60);
		nammaMetro.setUserName("Rachana NA");
		nammaMetro.setEmail("rachanaachar@gmail.com");
		nammaMetro.setTicket("QR Ticket");
		nammaMetro.setRating(4);
		nammaMetro.setNoOfPassengers(2000);
		nammaMetro.setLine1("Green Line");
		nammaMetro.setLine2("Purple Line");
		nammaMetro.setFrequency("30 mins");
		nammaMetro.setSince(2014);
		nammaMetro.setOwner("BMRCL");
		System.out.println(nammaMetro.getLanguage());
		System.out.println(nammaMetro.getFromStation());
		;
		System.out.println(nammaMetro.getToStation());
		System.out.println(nammaMetro.getFare());
		System.out.println(nammaMetro.getUserName());
		System.out.println(nammaMetro.getEmail());
		System.out.println(nammaMetro.getTicket());
		System.out.println(nammaMetro.getRating());
		System.out.println(nammaMetro.getNoOfPassengers());
		System.out.println(nammaMetro.getLine1());
		System.out.println(nammaMetro.getLine2());
		System.out.println(nammaMetro.getFrequency());
		System.out.println(nammaMetro.getSince());
		System.out.println(nammaMetro.getOwner());

		System.out.println("=====================================");
		System.out.println("Invoking mainMethod in Cred");
		Cred cred = new Cred();
		cred.setBankName("State Bank Of India");
		cred.setCardType("Credit");
		cred.setCompanyName("fintech");
		cred.setEmail("rachana@gmail.com");
		cred.setFounder("Kunal Shah");
		cred.setHeadquarter("Delhi");
		cred.setLanguage("English");
		cred.setPhoneNumber(8076453289l);
		cred.setPinNumber(890790);
		cred.setRating(5);
		cred.setSafe(true);
		cred.setSince(2019);
		cred.setType("free");
		cred.setUserName("Rachana");
		System.out.println(cred.getBankName());
		System.out.println(cred.getCardType());
		System.out.println(cred.getCompanyName());
		System.out.println(cred.getEmail());
		System.out.println(cred.getFounder());
		System.out.println(cred.getHeadquarter());
		System.out.println(cred.getLanguage());
		System.out.println(cred.getPhoneNumber());
		System.out.println(cred.getPinNumber());
		System.out.println(cred.getRating());
		System.out.println(cred.getSince());
		System.out.println(cred.getType());
		System.out.println(cred.getUserName());
		System.out.println(cred.isSafe());

	}

}
